twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:  
        # this is the path to the file that dictates the theme for errors
        - 'form/fields.html.twig'

when@test:
    twig:
        strict_variables: true
